---
- name: Add the knot-resolver repository key
  become: true
  ansible.builtin.apt_key:
    url: "https://download.opensuse.org/repositories/home:CZ-NIC:knot-resolver-latest/Debian_{{ ansible_distribution_major_version }}/Release.key"
    state: present

- name: Add the knot-resolver repository
  become: true
  ansible.builtin.apt_repository:
    repo: 'deb http://download.opensuse.org/repositories/home:/CZ-NIC:/knot-resolver-latest/Debian_{{ ansible_distribution_major_version }}/ /'
    filename: 'knot-resolver-latest'
    state: present

- name: Install knot resolver
  become: true
  ansible.builtin.apt:
    name:
      - knot-resolver
    state: present

- name: Install knot http module
  become: true
  ansible.builtin.apt:
    name:
      - knot-resolver-module-http
    state: present
  when: '"http" in dns_resolver_knot_modules'

- name: Configure kresd
  become: true
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/knot-resolver/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  with_items:
    - kresd.conf
  notify: Restart knot
