---
- name: add the knot-resolver repository key
  become: True
  apt_key:
    url: "https://download.opensuse.org/repositories/home:CZ-NIC:knot-resolver-latest/Debian_10/Release.key"
    state: present

- name: add the knot-resolver repository
  become: True
  apt_repository:
    repo: 'deb http://download.opensuse.org/repositories/home:/CZ-NIC:/knot-resolver-latest/Debian_10/ /'
    filename: 'knot-resolver-latest'
    state: present

- name: Install knot resolver
  become: True
  apt:
    name:
      - knot-resolver
    state: present

- name: Configure kresd
  become: True
  template:
    src: "{{ item }}.j2"
    dest: "/etc/knot-resolver/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - kresd.conf
  notify: restart knot
