---
- name: Install unbound resolver
  become: true
  ansible.builtin.apt:
    name:
      - unbound
      - unbound-anchor
    state: present

- name: Configure extra unbound optioms
  become: true
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/unbound/unbound.conf.d/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  with_items:
    - unbound.conf
  notify: Restart unbound
