---
- name: Restart unbound
  become: true
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
    enabled: true
  with_items:
    - unbound
    - unbound-resolvconf

- name: Restart knot
  become: true
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
    enabled: true
  with_items:
    - kresd@1.service
